name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  preload:
    runs-on: ubuntu-latest
    steps:
      - name: Preload legacy upload-artifact to avoid GitHub bug
        uses: actions/upload-artifact@v2
        with:
          name: dummy
          path: ./nonexistent
          if-no-files-found: ignore

  deploy:
    needs: preload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@v1
